### ISSUE TITLE
Commit user name is broken on slack message.

### ISSUE THREAD

**Issue by jllamas** [adamdehaven/slack-git-bot#1]
The name for the person who made the commit is garbled or incorrect.

It's displaying as "%cN"

<img width="595" alt="screen shot 2017-01-04 at 4 12 11 pm" src="https://cloud.githubusercontent.com/assets/38157/21664003/ae0c5a7e-d298-11e6-8091-f164b6424ab4.png">

I found some people had issues between SED versions. The server hosting the bare repo has Redhat EL running:
```
$ sed --version
GNU sed version 4.1.5
Copyright (C) 2003 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE,
to the extent permitted by law.
```

**Comment by adamdehaven** [comment]
It appears it's displaying the raw format string rather than the actual name. 

Is your example the only repo that's behaving this way? Or do you have multiple repositories (on different servers) that mimic the same behavior?

**Comment by jllamas** [comment]
I've only set it up on 1 repo. All of my repos are on the same server.

I'll add your script to another repo (same server) and see if continues to happen.

**Comment by jllamas** [comment]
It's having the same problem. Most likely because its on the same server.

<img width="453" alt="screen shot 2017-01-04 at 5 08 24 pm" src="https://cloud.githubusercontent.com/assets/38157/21665283/8434ec4a-d2a0-11e6-9e46-56af35bede4a.png">

I can setup a dummy repo on another box, like my desktop mac if you think that's going to help.

**Comment by adamdehaven** [comment]
This is a stupid question, but do you have your username setup on the server? 

Run `git config user.name` and see what it returns. That's the only thing I can think of off-hand unless it's your server configuration. 

`git config user.name 'Adam DeHaven'` to set your name

**Comment by jllamas** [comment]
The server is running a --bare repo. There are no users there.

git config user.name   returns an empty line.

Shouldn't it use the name from the commit message?

I'll try adding a name there to see what it does.

**Comment by adamdehaven** [comment]
Sorry, yes, that's what I meant

**Comment by jllamas** [comment]
I tried adding a name to the server repo but it didn't help. Same result.

$ git config user.name "Test"
$ git config user.name 
Test

<img width="389" alt="screen shot 2017-01-04 at 5 18 55 pm" src="https://cloud.githubusercontent.com/assets/38157/21665606/0e0445aa-d2a2-11e6-8391-dd6af5d1b811.png">

**Comment by jllamas** [comment]
It's working correctly from my local machine, using a bare repo. OS X 10.12 Sierra.

<img width="500" alt="screen shot 2017-01-04 at 5 24 42 pm" src="https://cloud.githubusercontent.com/assets/38157/21665865/1c96786c-d2a3-11e6-96ee-209334153abe.png">

Its seems it related to the Redhat server and probably the version of SED installed there.

**Comment by jllamas** [comment]
If you can setup a test bash script with sample input and the sed statement I can try to debug it on the Redhat server. I just don't have enough information to try and debug it otherwise. I'll have to break out those rusty awk and sed skills.

**Comment by adamdehaven** [comment]
Unfortunately I won't have time to look into it until this weekend. If you'll be monitoring this thread, I'll try to put something together for you to test with. 

If you find anything in the meantime, let me know

**Comment by jllamas** [comment]
We figured it out, the version of git on the server was 1.5.x and didn't support %cN only %cn. After updating git to 1.8.x it works perfect.

**Comment by adamdehaven** [comment]
Glad you figured it out. I had documented a test case for you but assumed it was a version issue.

**Comment by jllamas** [comment]
I only figured it out after trying to write a post-receive script from scratch. Thanks for your script though good stuff!!!
